[package]
name = "nexus"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "2.0"
crossterm = "0.28.1"
dirs = "5.0"
humantime = "2.1"
sha2 = "0.10"
signal-hook = "0.3"
bs58 = "0.5"
toml = "0.8"
